# Generated by Django 4.0.3 on 2022-04-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='defaults/profile_pic.jpg', null=True, upload_to='profile/')),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=15)),
                ('father_name', models.CharField(blank=True, default='', max_length=30)),
                ('mother_name', models.CharField(blank=True, default='', max_length=30)),
                ('adhaar_num', models.CharField(default='', max_length=20, unique=True)),
                ('mobile_number', models.CharField(default='', max_length=10)),
                ('registration_status', models.CharField(choices=[('NA', 'NotApplied'), ('PND', 'Pending'), ('AP', 'Approved')], default='NA', max_length=4)),
                ('authority', models.CharField(choices=[('N', 'None'), ('SA', 'SuperAdmin'), ('RA', 'RegionalAdmin')], default='N', max_length=4)),
                ('voter_id', models.CharField(default='None', max_length=20)),
            ],
        ),
    ]
