# Generated by Django 4.0.3 on 2022-04-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='authority',
            field=models.CharField(choices=[('none', 'None'), ('super', 'SuperAdmin'), ('regional', 'RegionalAdmin')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='registration_status',
            field=models.CharField(choices=[('na', 'NotApplied'), ('pending', 'Pending'), ('approved', 'Approved')], default='na', max_length=10),
        ),
    ]
