# Generated by Django 4.0.3 on 2022-04-18 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_userdata_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
