# Generated by Django 4.0.3 on 2022-04-23 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_pendingregistrations_region'),
        ('base', '0005_rename_adhaar_num_userdata_adhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.constituency'),
        ),
    ]
