# Generated by Django 4.0.4 on 2022-04-30 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_pendingregistrations_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=20)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.party')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.constituency')),
            ],
        ),
    ]
