# Generated by Django 4.0.4 on 2022-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_voted_electionresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.AddField(
            model_name='election',
            name='candidate',
            field=models.ManyToManyField(to='elections.candidate'),
        ),
    ]
