# Generated by Django 4.0.4 on 2022-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_remove_candidate_election_election_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='candidate',
        ),
        migrations.AddField(
            model_name='election',
            name='candidates',
            field=models.ManyToManyField(blank=True, null=True, to='elections.candidate'),
        ),
        migrations.AlterField(
            model_name='election',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, to='elections.constituency'),
        ),
    ]
