# Generated by Django 4.0.4 on 2022-05-08 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_remove_election_candidate_election_candidates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionresults',
            name='candidate',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.candidate'),
        ),
        migrations.AlterField(
            model_name='electionresults',
            name='election',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
        migrations.AlterField(
            model_name='electionresults',
            name='party',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.party'),
        ),
        migrations.AlterField(
            model_name='electionresults',
            name='region',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.constituency'),
        ),
    ]
