# Generated by Django 4.0.4 on 2022-05-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_electionresults_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='parties',
            field=models.ManyToManyField(blank=True, null=True, to='elections.party'),
        ),
        migrations.AddField(
            model_name='party',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, to='elections.constituency'),
        ),
    ]
