# Generated by Django 4.0.4 on 2022-05-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_election_parties_party_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='regions',
        ),
    ]
