# Generated by Django 4.0.4 on 2022-05-31 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_remove_party_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='visible',
        ),
        migrations.CreateModel(
            name='BB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lh', models.CharField(max_length=80)),
                ('h', models.CharField(max_length=80)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
            ],
        ),
    ]
